apiVersion: v2
type: application
version: 0.1.0
name: knowyourtaxes
appVersion: "1.0"
description: "Know Your Taxes"
dependencies:
  - name: postgresql
    version: 10.16.2
    repository: https://charts.bitnami.com/bitnami
